### ISSUE TITLE
jasmine_chromeapp runs integration tests from previous tests in another repo

### ISSUE THREAD

**Issue by lucyhe** [freedomjs/freedom-social-xmpp#88]
Noticed this while @salomegeo and I were working on https://github.com/uProxy/uproxy/pull/801.
After running 'grunt jasmine_chromeapp' in /freedom-social-xmpp, when we tried to run integration tests in /uproxy it was still the integration tests from freedom-social-xmpp being run. Killing all selenium processes would allow uproxy integration tests to run.

**Comment by willscott** [comment]
do you have the `keepRunner` option true? if so we don't shut down selenium, because doing so ends up killing the browser. I don't know if there's a good way to do that.

**Comment by salomegeo** [comment]
Yes, keepRunner was set to true.

**Comment by salomegeo** [comment]
also if we run integration test in upxoy repository with keepRunner set to true, and then again with it set to false, and then try running test in freedom-social-xmpp it gives error message "Failed to load extension from <path to urpxy>/.build. Manifest file is missing of unreadable"

**Comment by willscott** [comment]
Right, so if you keep the runner, the previous selenium will still be
running.  The new selenium you start in a subsequent run isn't getting
access to the port (since the previous one has already bound it), so things
will break.

We can try to have the grunt task wait until chrome is quit so that it can
also shut down selenium, however the chrome app launch option isn't really
fully supported, and doesn't actually connect back to selenium, so I'm not
sure what sort of monitoring of the launched chrome instance we'll actually
be able to do.

**Comment by iislucas** [comment]
The behavior I'd expect is that a new grunt integration test run would kill the old one. That seems like a solution?

**Comment by willscott** [comment]
I don't think the new run would have any handle to find the previous
process - which is spawned with the child_process module, iirc.  Having
grunt test running `pkill` on my machine would make me uncomfortable.
Probably requires looking into how to do this safely.

**Comment by salomegeo** [comment]
can we just have a separate task to kill selenium?

**Comment by willscott** [comment]
Also tracking in https://github.com/willscott/grunt-jasmine-chromeapp/issues/1

**Comment by ryscheng** [comment]
I'm going to close this, since it's a bug with grunt-jasmine-chromeapp and not freedom-social-xmpp
